INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(1, 'Copper Penny', 'styles/CopperPenny/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(2, 'Aqua Blue', 'styles/AquaBlue/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(3, 'African Violet', 'styles/AfricanViolet/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(4, 'Coffee Brown', 'styles/CoffeeBrown/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(5, 'Escastic Blue', 'styles/EscasticBlue/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(6, 'Feminine Pink', 'styles/FemininePink/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(7, 'Pale Green', 'styles/PaleGreen/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(8, 'Pantone Skin', 'styles/PantoneSkin/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(9, 'Parrot Green', 'styles/ParrotGreen/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_css` (`nCSSId`, `vCSSName`, `vCSSURL`, `dDate`) VALUES(10, 'Tan Brick', 'styles/TanBrick/style.css', '2012-10-08 10:50:03');
INSERT INTO `sptbl_lookup` (`nLookUpId` ,`vLookUpName` ,`vLookUpValue`) VALUES (NULL , 'NewTicketAutoReturnMail', '1');
INSERT INTO `sptbl_lookup` (`nLookUpId` ,`vLookUpName` ,`vLookUpValue`) VALUES (NULL , 'Theme', '1');
INSERT INTO `sptbl_lookup` (`nLookUpId` ,`vLookUpName` ,`vLookUpValue`) VALUES (NULL , 'Version', '4.2');
INSERT INTO sptbl_lang (`vLangCode` ,`VLangDesc`) VALUES ('de','German');
INSERT INTO sptbl_lang (`vLangCode` ,`VLangDesc`) VALUES ('fr','French');
INSERT INTO sptbl_lang (`vLangCode` ,`VLangDesc`) VALUES ('es','Spanish');
INSERT INTO sptbl_lookup VALUES (NULL ,'LiveChat', '1');
INSERT INTO `sptbl_lookup` VALUES (NULL , 'AD_AUTHENTICATION', 'N');
INSERT INTO `sptbl_lookup` VALUES (NULL , 'AD_USER', '');
INSERT INTO `sptbl_lookup` VALUES (NULL , 'AD_PASS', '');
INSERT INTO `sptbl_lookup` VALUES (NULL , 'AD_DOMAIN', '');
INSERT INTO `sptbl_lookup` VALUES (NULL , 'AD_HOST', '');
INSERT INTO `sptbl_lookup` VALUES (NULL , 'AD_USER_DIR', 'CN=USER');