INSERT IGNORE INTO `goStores_Vista_admins` (`id`, `admin_name`, `admin_pword`, `profile_img`, `settings`, `custom`, `category`, `products`, `feedback`, `users`, `orders`, `refund`, `promocodes`, `websitecontent`, `reports`, `homepage`, `help`, `adminusers`, `newsletter`, `newsletterusers`, `sentnewsletters`, `giftcards`, `banners`, `giftcardusers`, `offers`, `customer_groups`, `tags`, `email`, `blog_pword`) VALUES
	(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', '', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'anoop.v@armiasystems.com', 'admin');

INSERT IGNORE INTO `goStores_Vista_advertisements` (`id`, `adfile`, `template_id`, `position`, `status`) VALUES
	(1, 'AD1566380095.png', 1, 1, 1),
	(2, 'AD1566380120.png', 1, 2, 1),
	(3, 'AD1561362763.png', 2, 1, 1),
	(4, 'AD1566907214.png', 2, 2, 1),
	(5, 'AD1566907225.png', 2, 3, 1),
	(6, 'AD1566907235.png', 2, 4, 1),
	(7, 'AD1567148723.png', 3, 1, 1),
	(8, 'AD1567148714.png', 3, 3, 1),
	(9, 'AD1567164132.png', 4, 1, 1),
	(10, 'AD1567164187.png', 4, 2, 1),
	(11, 'AD1567404582.png', 5, 1, 1),
	(12, 'AD1567514694.png', 5, 2, 1),
	(13, 'AD1567514685.png', 5, 3, 1),
	(14, 'AD1566382270.png', 1, 3, 1);

INSERT IGNORE INTO `goStores_Vista_banners` (`id`, `bannerfile`, `template_id`, `status`, `displayorder`, `bannertitle`, `bannerdata`) VALUES
	(1, 'BAN1566308950.png', 1, 1, 2, 'special offer', '20 % off for all products'),
	(2, 'BAN1566308941.png', 1, 1, 1, 'NEW YEAR OFFER', 'special offer for all products'),
	(3, 'BAN1566308930.png', 1, 1, 3, 'Womens Only Wednesdays', 'Upto 70% off'),
	(4, 'BAN1567063242.png', 3, 1, 1, 'BEST OFFER', 'PURCHASE YOUR GUN'),
	(5, 'BAN1567063855.png', 3, 1, 2, 'THIS MONTH OFFER', 'PURCHASE YOUR GUN'),
	(6, 'BAN1567063845.png', 3, 1, 3, 'THIS WEEK OFFER', 'PURCHASE YOUR GUN'),
	(7, 'BAN1567165211.png', 4, 1, 3, 'This Week Offer', '25% Offer'),
	(8, 'BAN1567165917.png', 4, 1, 2, 'This Month Offer', '10% Offer'),
	(9, 'BAN1566909335.png', 2, 1, 1, 'Big Offer', '50%  Offer'),
	(10, 'BAN1566912594.png', 2, 1, 2, 'Summer Offer', '15% Offer'),
	(11, 'BAN1566912618.png', 2, 1, 3, 'This Week Offer', '10% Offer'),
	(12, 'BAN1567505261.png', 5, 1, 1, 'The Spring racing edition', 'Spring Collection'),
	(13, 'BAN1567505208.png', 5, 1, 2, 'New collection ', 'Made for her'),
	(14, 'BAN1567504747.png', 5, 1, 3, 'Looking for the best price', 'Summer Collection'),
	(15, 'BAN1567165163.png', 4, 1, 1, 'This Day Offer', '5% Offer');

INSERT IGNORE INTO `goStores_Vista_categories` (`id`, `cname`, `seo_slug`, `parent_id`, `custom_combination`, `is_from_invsrc`) VALUES
	(1, 'Root', NULL, 0, '', 0),
	(2, 'Miscellaneous', 'miscellaneous', 1, '', 0),
	(3, 'Miscellaneous', 'miscellaneous', 2, '', 0);

INSERT IGNORE INTO `goStores_Vista_cmspages` (`id`, `title`, `content`, `type`, `status`) VALUES
	(1, 'Order confirm mail', '<p>Hi [User_Name],</p>\r\n\r\n<p>Your order has been successfully placed at [SITE_NAME]. The order details are as follows.</p>\r\n\r\n<p>[ORDER_DETAILS]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Regards,</p>\r\n\r\n<p>Team [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(2, 'Registration intimation mail to admin', '<p>Hi Administrator,<br />\r\nA new user [User_Name] is registered with [SITE_NAME].</p>\r\n\r\n<p>Regards,<br />\r\nTeam [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(3, 'AboutUS', '<h2>Who We Are</h2>\r\n\r\n<p>Hello, and welcome to Online Toys....</p>\r\n\r\n<p>Online Toys is owned and operated by our family owned company - American Online Commerce Pty. Ltd. We are a purely internet based toy store which means we specialise in the sale of toys only through the World Wide Web. We are an independent toy retailer and we are located at Los Angeles. Our web site www.etoys.com officially opened for business October 2010 with the ultimate aim of one day becoming America&#39;s best known, and loved, online toy store.</p>\r\n\r\n<p>We despatch orders US-wide and to several international destinations. We allow customer pickups, customer enquiries via phone or email, and in many cases we can ship orders same day. Our warehouse allows us to hold stock while our web site tracks stock in real-time so we can despatch orders quickly and efficiently at all times.</p>\r\n\r\n<p>Our goals are to:</p>\r\n\r\n<table border="0" cellpadding="0" cellspacing="5" style="width:100%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<ul>\r\n				<li>Provide our customers with a great selection of toys,</li>\r\n				<li>Offer the toys at the lowest possible price,</li>\r\n				<li>Provide a friendly, fast, and reliable service at all times,</li>\r\n				<li>Give our customers total piece-of-mind should anything go wrong,</li>\r\n				<li>And make our store as easy as possible to use and navigate.</li>\r\n			</ul>\r\n			</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n', 'content', 'Y'),
	(4, 'Forgot password mail', '<p>Hi [User_Name],</p>\r\n\r\n<p>Your Password on [SITE_NAME] has been reset.</p>\r\n\r\n<p>Your new password is :&nbsp; [PASSWORD]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Regards,</p>\r\n\r\n<p>Team [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(5, 'Registration confirm mail', '<p>Hi [User_Name],</p>\r\n\r\n<p>Your Registration with&nbsp;&nbsp;[SITE_NAME] has been completed.</p>\r\n\r\n<p>User Name: [User_Name]</p>\r\n\r\n<p>Password:&nbsp;&nbsp;[PASSWORD]</p>\r\n\r\n<p>[LOGIN_URL]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Regards,</p>\r\n\r\n<p>Team [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(6, 'Order status change mail', '<p>Hi [User_Name],</p>\r\n\r\n<p>Your order status has been changed at [SITE_NAME]. The order details are as follows.</p>\r\n\r\n<p>[ORDER_DETAILS]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Regards,</p>\r\n\r\n<p>Team [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(7, 'FAQ', '<p><b>Frequently Asked Questions</b>&nbsp;</p>\r\n<p><strong>Q:&nbsp;</strong> &nbsp;&nbsp;&nbsp; My toy has arrived broken. What do I do?<br />\r\n<strong>A: </strong>&nbsp;&nbsp;&nbsp; If you suspect that the toy you ordered from us is damaged, please do not accept delivery. Ask the driver/postman that it be returned to sender by crossing out your delivery address and writing, in big letters, &quot;RTS&quot; (Return To Sender). Notify us of what\'s happened and we will take care of the rest by having a replacement toy sent out to you once the damaged toy is received by us.<br />\r\n<br />\r\nIf, on the other hand, you accepted delivery and discovered your toy to be broken much later, don\'t stress. The first thing to do is to notify us about the problem, we will provide you with a special number called a Return Merchandise Authority (RMA) number and further instructions. Repack the damaged toy, in its original packaging, together with the original receipt (if you have one) and everything else that came with it and return it back to us using the \'Reply Paid\' address we give you. A replacement toy will be sent to you once the damaged toy is received by us.<br />\r\n<br />\r\n<strong>Q:&nbsp;</strong> &nbsp;&nbsp;&nbsp; How does the Customer Reward Points programme work?<br />\r\n<strong>A: </strong>&nbsp;&nbsp;&nbsp; In a nutshell, you will receive 10 points for every $1 you spend. Toys labelled &quot;BONUS&quot; will reward you with more points (sometimes twice more). You can accumulate your points (and save for something big) or you can use them upon subsequent visits. The choice is yours. To convert points back into dollars, you will need 250 points to make up $1. Please click here for further information and click on the &quot;Terms &amp; Conditions&quot; tab above to read our Terms &amp; Conditions.<br />\r\n<br />\r\n<br />\r\n<strong>Q:&nbsp;</strong> &nbsp;&nbsp;&nbsp; I bought the wrong toy. What do I do?<br />\r\nA: &nbsp;&nbsp;&nbsp; It is important that when selecting the toy you want that you do so carefully. We understand that many toys look the same, some of them have very similar names, while others do exactly the same things, however, we cannot be held responsible if you make a wrong selection or change your mind.<br />\r\n<br />\r\nIf you are unsure about anything, we are here to help. Please use our Live Help service, email, or call us by telephone and ask us questions that will help you make the right choice. <br />\r\n<br />\r\n<strong>Q:&nbsp;</strong> &nbsp;&nbsp;&nbsp; Can I pay by cheque?<br />\r\n<strong>A: &nbsp;</strong>&nbsp;&nbsp; Yes you can. In addition to credit cards, we also accept bank cheques, personal cheques, and money orders. But please keep in mind that no orders will be despatched until cheque payments have been cleared by the bank. Cheques normally take around 3 working days to clear.<br />\r\n<br />\r\n<strong>Q:&nbsp;</strong> &nbsp;&nbsp;&nbsp; I\'ve selected a gift-tag, why cant I include a message?<br />\r\n<strong>A: </strong>&nbsp;&nbsp;&nbsp; Gift-tags generally are not very big which means after including the recipients and senders names there generally isn\'t much room for anything else. However, our Greeting Cards do have the option to include messages if required.<br />\r\n<br />\r\n<strong>Q:&nbsp;</strong> &nbsp;&nbsp;&nbsp; Do you sell/trade on eBay?<br />\r\n<strong>A: &nbsp;</strong>&nbsp;&nbsp; No, we don\'t.</p>', 'content', 'Y'),
	(8, 'Terms', '<p>TERMS OF USE</p>\n\n<p>Updated July 1, 2019</p>\n\n<p>This website is owned by Iscripts Gostores. These &ldquo;Terms of Use&rdquo; inform visitors of the rules and policies that govern this website. By using this website, you agree to abide by these terms. We may update this Agreement from time to time. If you do not agree with these Terms of Use, or any of our posted guidelines, please do not use this website. Website Content This website contains materials supplied by MRA and its affiliates, parents, and subsidiaries, as well as other sources, such as third party operational and marketing or manufacturing partners, and is protected by copyrights, trademarks, service marks, patents, trade secrets, or other proprietary rights and laws.</p>\n\n<p>Although we try to ensure that the material on this website is accurate and error-free, from time to time the materials may include inaccuracies or typographical errors. We are not responsible for any such inaccuracies or errors. We reserve the right to make changes and update any material and/or information contained on this website without prior notice.</p>\n\n<p>Except as expressly authorized by MRA, visitors may not copy, reproduce, republish, distribute, sell, license, rent, publicly display or perform, adapt or create a derivative work of, in any manner, any material, content or design elements obtained from this site, including code and software (collectively, the &ldquo;material&rdquo;).</p>\n\n<p>Notwithstanding the above, visitors may print or download the material from this site only for personal or non-commercial use, provided that the visitor does not republish the material and keeps intact all copyright, trademarks, service marks, patent and other proprietary notices.</p>\n\n<p>Copyright MRA respects the intellectual property rights of third parties and is committed to complying with all U.S. copyright and related laws. This policy is in addition to and does not affect or modify any other rights that MRA may have under law or contract. If a copyright holder believes in good faith that materials being hosted by MRA or otherwise stored on its network infringe on its rights, the copyright holder (or its agent) may send MRA a notification in accordance with the requirements set forth in the DMCA, requesting that MRA remove or block access to the infringing material.</p>\n\n<p>The notification must be emailed to: info@globusgear.com Third Party Links This website may contain links and pointers to other sites and resources on the Internet controlled by third parties.</p>\n\n<p>These links are provided solely as a convenience to our visitors and do not constitute an endorsement by MRA, its parents, affiliates or subsidiaries of any third party resources or content. Links do not imply that MRA sponsors, is affiliated or associated with, or otherwise recommends, certifies or endorses the third party link or site. Any concerns regarding external links or websites should be directed to the respective website administrator or system operator. Disclaimer of Warranties This website is provided &ldquo;AS IS.&rdquo; You agree that your use of this website is at your sole risk. MRA does not warrant, either expressly or by implication, the accuracy of any materials or information provided on the site or their suitability for any particular purpose, and expressly disclaims all warranties, including, but not limited to, warranties of merchantability or fitness for a particular purpose. Although the information provided to visitors on this site is obtained or compiled from sources we believe to be reliable, MRA cannot and does not guarantee the accuracy, validity, timeliness, completeness or reliability of any information or data made available to visitors or its suitability for any particular purpose.</p>\n\n<p>Neither MRA, nor any of its parents, partners, affiliates, subsidiaries, members, directors, officer, employees, agents, operational providers are liable or shall have responsibility of any kind to any visitor for any loss or damage that a visitor incurs in the event of (i) any failure or interruption of this site; (ii) any act or omission of any third party involved in making this site or the data contained herein available to visitors; (iii) any other cause relating to a visitor&rsquo;s access or use, or inability to access or use, any portion of this site or Materials on this site; (iv) or from any visitor&rsquo;s failure to comply with this Agreement, whether or not the circumstances giving rise to such cause may have been within the control of MRA or any vendor providing software, services or support. In no event will MRA, its parents, partners, affiliates, subsidiaries, members, officers or employees be liable to any visitor for any direct, indirect, consequential, or incidental damages or any other loss or damages of any kind.</p>\n\n<p>Please be advised that once you leave our website, your use of the Internet will be governed by the terms of usage agreements and privacy policies, if any, of the particular website that you are accessing, including those of our operational providers, vendors and partners.</p>\n\n<p>MRA, its parents, partners, affiliates, subsidiaries, members, directors, officers, employees and agents will not be responsible or liable for the content, activities, or privacy practices of the other websites, or any loss or damage that could result from leaving our website.</p>\n\n<p>&nbsp;</p>\n', 'content', 'Y'),
	(12, 'Order payment received mail', '<p>Hi [User_Name],</p>\r\n\r\n<p>Your order payment has been received at [SITE_NAME]. The order details are as follows.</p>\r\n\r\n<p>[ORDER_DETAILS]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Regards,</p>\r\n\r\n<p>Team [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(9, 'Admin order confirm mail', '<p>Hi Administrator,</p>\r\n\r\n<p>An Order has been successfully placed at [SITE_NAME]. The order details are as follows.</p>\r\n\r\n<p>[ORDER_DETAILS]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Regards,</p>\r\n\r\n<p>Team [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(10, 'Testimonials', 'Add Testimonials Here...............................', 'content', 'N'),
	(11, 'Community', '<p>Add Community details Here...............................</p>\r\n', 'content', 'N'),
	(14, 'Contact us mail for admin', '<p>Hi Administrator,</p>\r\n\r\n<p>A new customer feedback has been added on the site. The details are as follows:</p>\r\n\r\n<p>Customer Name: [name]</p>\r\n\r\n<p>Email: [email]</p>\r\n\r\n<p>Message: [message]</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Regards,</p>\r\n\r\n<p>Team [SITE_NAME]</p>\r\n', 'email', 'Y'),
	(15, 'FFL mail for admin', '<p>Hi Administrator,</p>\n\n<p>Please find the FFL ID and Special Occupational Taxpayer (SOT) license for the seller:</p>\n\n<p>Store Name: [site_name] </p>\n\n<p>Store Address: [store_address] </p>\n\n<p>Site Administrator Email: [site_admin] </p>\n\n<p>FFL ID: [ffl_id]</p>\n\n<p>&nbsp;</p>\n\n<p>Regards,</p>\n\n<p>Team [SITE_NAME]</p>', 'email', 'Y'),
	(16, 'Inventory email', '<p>Hi Administrator,<br />\nPlease find the following details</p>\n\n<p>[INV_DATA] </p>\n\n<p>Regards,<br />\nTeam [SITE_NAME]</p>\n', 'email', 'Y'),
	(17, 'Ruger Main Block', '<h2 itemprop="headline"><i class="theme-clr">WHO WE ARE</i> INTRODUCING</h2>\r\n                                    <p itemprop="description">With ste-of-the-art indoor training facilities and full sece custom shop on lion, e can accomm most reests. All modern weapon enthussts can te our broad services and real-world, experienc. state-of-the-art ilities and full service.</p>', 'block', 'Y'),
	(18, 'Ruger Main Block Side1', '<h5><a href="#" title="">TARGET PRACTICE</a></h5>\r\n\r\n<p>With state-of-the-art indoor training faciliti service lorim custom</p>\r\n', 'block', 'Y'),
	(19, 'Ruger Main Block Side2', '<h5><a href="#" title="">SECOND AMNEDMENT</a></h5>\r\n\r\n<p>With state-of-the-art indoor training faciliti service lorim custom</p>\r\n', 'block', 'Y'),
	(20, 'Ruger Main Block Side3', '<h5 itemprop="headline"><a href="#" title="" itemprop="url">SHOOT RANGE</a></h5>\r\n                                        <p itemprop="description">With state-of-the-art indoor training faciliti service lorim custom </p>\r\n            ', 'block', 'Y'),
	(21, 'Ruger Main Block Side4', '<h5 itemprop="headline"><a href="#" title="" itemprop="url">TRAINING CENTER</a></h5>\r\n                                        <p itemprop="description">With state-of-the-art indoor training faciliti service lorim custom </p>', 'block', 'Y');

INSERT IGNORE INTO `goStores_Vista_countries` (`country_id`, `country_name`, `country_iso_code_2`) VALUES
	(1, 'Afghanistan', 'AF'),
	(2, 'Albania', 'AL'),
	(3, 'Algeria', 'DZ'),
	(4, 'American Samoa', 'AS'),
	(5, 'Andorra', 'AD'),
	(6, 'Angola', 'AO'),
	(7, 'Anguilla', 'AI'),
	(8, 'Antarctica', 'AQ'),
	(9, 'Antigua and Barbuda', 'AG'),
	(10, 'Argentina', 'AR'),
	(11, 'Armenia', 'AM'),
	(12, 'Aruba', 'AW'),
	(13, 'Australia', 'AU'),
	(14, 'Austria', 'AT'),
	(15, 'Azerbaijan', 'AZ'),
	(16, 'Bahamas', 'BS'),
	(17, 'Bahrain', 'BH'),
	(18, 'Bangladesh', 'BD'),
	(19, 'Barbados', 'BB'),
	(20, 'Belarus', 'BY'),
	(21, 'Belgium', 'BE'),
	(22, 'Belize', 'BZ'),
	(23, 'Benin', 'BJ'),
	(24, 'Bermuda', 'BM'),
	(25, 'Bhutan', 'BT'),
	(26, 'Bolivia', 'BO'),
	(27, 'Bosnia and Herzegowina', 'BA'),
	(28, 'Botswana', 'BW'),
	(29, 'Bouvet Island', 'BV'),
	(30, 'Brazil', 'BR'),
	(31, 'British Indian Ocean Territory', 'IO'),
	(32, 'Brunei Darussalam', 'BN'),
	(33, 'Bulgaria', 'BG'),
	(34, 'Burkina Faso', 'BF'),
	(35, 'Burundi', 'BI'),
	(36, 'Cambodia', 'KH'),
	(37, 'Cameroon', 'CM'),
	(38, 'Canada', 'CA'),
	(39, 'Cape Verde', 'CV'),
	(40, 'Cayman Islands', 'KY'),
	(41, 'Central African Republic', 'CF'),
	(42, 'Chad', 'TD'),
	(43, 'Chile', 'CL'),
	(44, 'China', 'CN'),
	(45, 'Christmas Island', 'CX'),
	(46, 'Cocos (Keeling) Islands', 'CC'),
	(47, 'Colombia', 'CO'),
	(48, 'Comoros', 'KM'),
	(49, 'Congo', 'CG'),
	(50, 'Cook Islands', 'CK'),
	(51, 'Costa Rica', 'CR'),
	(52, 'Cote D\'Ivoire', 'CI'),
	(53, 'Croatia', 'HR'),
	(54, 'Cuba', 'CU'),
	(55, 'Cyprus', 'CY'),
	(56, 'Czech Republic', 'CZ'),
	(57, 'Denmark', 'DK'),
	(58, 'Djibouti', 'DJ'),
	(59, 'Dominica', 'DM'),
	(60, 'Dominican Republic', 'DO'),
	(61, 'East Timor', 'TP'),
	(62, 'Ecuador', 'EC'),
	(63, 'Egypt', 'EG'),
	(64, 'El Salvador', 'SV'),
	(65, 'Equatorial Guinea', 'GQ'),
	(66, 'Eritrea', 'ER'),
	(67, 'Estonia', 'EE'),
	(68, 'Ethiopia', 'ET'),
	(69, 'Falkland Islands (Malvinas)', 'FK'),
	(70, 'Faroe Islands', 'FO'),
	(71, 'Fiji', 'FJ'),
	(72, 'Finland', 'FI'),
	(73, 'France', 'FR'),
	(74, 'France, Metropolitan', 'FX'),
	(75, 'French Guiana', 'GF'),
	(76, 'French Polynesia', 'PF'),
	(77, 'French Southern Territories', 'TF'),
	(78, 'Gabon', 'GA'),
	(79, 'Gambia', 'GM'),
	(80, 'Georgia', 'GE'),
	(81, 'Germany', 'DE'),
	(82, 'Ghana', 'GH'),
	(83, 'Gibraltar', 'GI'),
	(84, 'Greece', 'GR'),
	(85, 'Greenland', 'GL'),
	(86, 'Grenada', 'GD'),
	(87, 'Guadeloupe', 'GP'),
	(88, 'Guam', 'GU'),
	(89, 'Guatemala', 'GT'),
	(90, 'Guinea', 'GN'),
	(91, 'Guinea-bissau', 'GW'),
	(92, 'Guyana', 'GY'),
	(93, 'Haiti', 'HT'),
	(94, 'Heard and Mc Donald Islands', 'HM'),
	(95, 'Honduras', 'HN'),
	(96, 'Hong Kong', 'HK'),
	(97, 'Hungary', 'HU'),
	(98, 'Iceland', 'IS'),
	(99, 'India', 'IN'),
	(100, 'Indonesia', 'ID'),
	(101, 'Iran (Islamic Republic of)', 'IR'),
	(102, 'Iraq', 'IQ'),
	(103, 'Ireland', 'IE'),
	(104, 'Israel', 'IL'),
	(105, 'Italy', 'IT'),
	(106, 'Jamaica', 'JM'),
	(107, 'Japan', 'JP'),
	(108, 'Jordan', 'JO'),
	(109, 'Kazakhstan', 'KZ'),
	(110, 'Kenya', 'KE'),
	(111, 'Kiribati', 'KI'),
	(112, 'Korea, Democratic People\'s Republic of', 'KP'),
	(113, 'Korea, Republic of', 'KR'),
	(114, 'Kuwait', 'KW'),
	(115, 'Kyrgyzstan', 'KG'),
	(116, 'Lao People\'s Democratic Republic', 'LA'),
	(117, 'Latvia', 'LV'),
	(118, 'Lebanon', 'LB'),
	(119, 'Lesotho', 'LS'),
	(120, 'Liberia', 'LR'),
	(121, 'Libyan Arab Jamahiriya', 'LY'),
	(122, 'Liechtenstein', 'LI'),
	(123, 'Lithuania', 'LT'),
	(124, 'Luxembourg', 'LU'),
	(125, 'Macau', 'MO'),
	(126, 'Macedonia, The Former Yugoslav Republic of', 'MK'),
	(127, 'Madagascar', 'MG'),
	(128, 'Malawi', 'MW'),
	(129, 'Malaysia', 'MY'),
	(130, 'Maldives', 'MV'),
	(131, 'Mali', 'ML'),
	(132, 'Malta', 'MT'),
	(133, 'Marshall Islands', 'MH'),
	(134, 'Martinique', 'MQ'),
	(135, 'Mauritania', 'MR'),
	(136, 'Mauritius', 'MU'),
	(137, 'Mayotte', 'YT'),
	(138, 'Mexico', 'MX'),
	(139, 'Micronesia, Federated States of', 'FM'),
	(140, 'Moldova, Republic of', 'MD'),
	(141, 'Monaco', 'MC'),
	(142, 'Mongolia', 'MN'),
	(143, 'Montserrat', 'MS'),
	(144, 'Morocco', 'MA'),
	(145, 'Mozambique', 'MZ'),
	(146, 'Myanmar', 'MM'),
	(147, 'Namibia', 'NA'),
	(148, 'Nauru', 'NR'),
	(149, 'Nepal', 'NP'),
	(150, 'Netherlands', 'NL'),
	(151, 'Netherlands Antilles', 'AN'),
	(152, 'New Caledonia', 'NC'),
	(153, 'New Zealand', 'NZ'),
	(154, 'Nicaragua', 'NI'),
	(155, 'Niger', 'NE'),
	(156, 'Nigeria', 'NG'),
	(157, 'Niue', 'NU'),
	(158, 'Norfolk Island', 'NF'),
	(159, 'Northern Mariana Islands', 'MP'),
	(160, 'Norway', 'NO'),
	(161, 'Oman', 'OM'),
	(162, 'Pakistan', 'PK'),
	(163, 'Palau', 'PW'),
	(164, 'Panama', 'PA'),
	(165, 'Papua New Guinea', 'PG'),
	(166, 'Paraguay', 'PY'),
	(167, 'Peru', 'PE'),
	(168, 'Philippines', 'PH'),
	(169, 'Pitcairn', 'PN'),
	(170, 'Poland', 'PL'),
	(171, 'Portugal', 'PT'),
	(172, 'Puerto Rico', 'PR'),
	(173, 'Qatar', 'QA'),
	(174, 'Reunion', 'RE'),
	(175, 'Romania', 'RO'),
	(176, 'Russian Federation', 'RU'),
	(177, 'Rwanda', 'RW'),
	(178, 'Saint Kitts and Nevis', 'KN'),
	(179, 'Saint Lucia', 'LC'),
	(180, 'Saint Vincent and the Grenadines', 'VC'),
	(181, 'Samoa', 'WS'),
	(182, 'San Marino', 'SM'),
	(183, 'Sao Tome and Principe', 'ST'),
	(184, 'Saudi Arabia', 'SA'),
	(185, 'Senegal', 'SN'),
	(186, 'Seychelles', 'SC'),
	(187, 'Sierra Leone', 'SL'),
	(188, 'Singapore', 'SG'),
	(189, 'Slovakia (Slovak Republic)', 'SK'),
	(190, 'Slovenia', 'SI'),
	(191, 'Solomon Islands', 'SB'),
	(192, 'Somalia', 'SO'),
	(193, 'South Africa', 'ZA'),
	(194, 'South Georgia and the South Sandwich Islands', 'GS'),
	(195, 'Spain', 'ES'),
	(196, 'Sri Lanka', 'LK'),
	(197, 'St. Helena', 'SH'),
	(198, 'St. Pierre and Miquelon', 'PM'),
	(199, 'Sudan', 'SD'),
	(200, 'Suriname', 'SR'),
	(201, 'Svalbard and Jan Mayen Islands', 'SJ'),
	(202, 'Swaziland', 'SZ'),
	(203, 'Sweden', 'SE'),
	(204, 'Switzerland', 'CH'),
	(205, 'Syrian Arab Republic', 'SY'),
	(206, 'Taiwan', 'TW'),
	(207, 'Tajikistan', 'TJ'),
	(208, 'Tanzania, United Republic of', 'TZ'),
	(209, 'Thailand', 'TH'),
	(210, 'Togo', 'TG'),
	(211, 'Tokelau', 'TK'),
	(212, 'Tonga', 'TO'),
	(213, 'Trinidad and Tobago', 'TT'),
	(214, 'Tunisia', 'TN'),
	(215, 'Turkey', 'TR'),
	(216, 'Turkmenistan', 'TM'),
	(217, 'Turks and Caicos Islands', 'TC'),
	(218, 'Tuvalu', 'TV'),
	(219, 'Uganda', 'UG'),
	(220, 'Ukraine', 'UA'),
	(221, 'United Arab Emirates', 'AE'),
	(222, 'United Kingdom', 'GB'),
	(223, 'United States', 'US'),
	(224, 'United States Minor Outlying Islands', 'UM'),
	(225, 'Uruguay', 'UY'),
	(226, 'Uzbekistan', 'UZ'),
	(227, 'Vanuatu', 'VU'),
	(228, 'Vatican City State (Holy See)', 'VA'),
	(229, 'Venezuela', 'VE'),
	(230, 'Viet Nam', 'VN'),
	(231, 'Virgin Islands (British)', 'VG'),
	(232, 'Virgin Islands (U.S.)', 'VI'),
	(233, 'Wallis and Futuna Islands', 'WF'),
	(234, 'Western Sahara', 'EH'),
	(235, 'Yemen', 'YE'),
	(236, 'Yugoslavia', 'YU'),
	(237, 'Zaire', 'ZR'),
	(238, 'Zambia', 'ZM'),
	(239, 'Zimbabwe', 'ZW');

INSERT IGNORE INTO `goStores_Vista_currencies` (`id`, `code`, `name`, `logo`) VALUES
	(1, 'USD', 'USD - U.S. Dollars', '$'),
	(2, 'AUD', 'AUD - Australian Dollars', '$'),
	(3, 'GBP', 'GBP - British Pounds', 'ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â£'),
	(4, 'CAD', 'CAD - Canadian Dollars', '$'),
	(5, 'CZK', 'CZK - Czech Koruna', 'Kc'),
	(6, 'DKK', 'DKK - Danish Kroner', 'kr'),
	(7, 'EUR', 'EUR - Euros', 'ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬'),
	(8, 'HKD', 'HKD - Hong Kong Dollars', 'HK$'),
	(9, 'HUF', 'HUF - Hungarian Forint', 'Ft'),
	(10, 'ILS', 'ILS - Israeli New Shekels', '?'),
	(11, 'JPY', 'JPY - Japanese Yen', ''),
	(12, 'MXN', 'MXN - Mexican Pesos', '$'),
	(13, 'NZD', 'NZD - New Zealand Dollars', '$'),
	(14, 'NOK', 'NOK - Norwegian Kroner', 'kr'),
	(15, 'PLN', 'PLN - Polish Zlotych', 'zl'),
	(16, 'SGD', 'SGD - Singapore Dollars', '$'),
	(17, 'SEK', 'SEK - Swedish Kronor', 'kr'),
	(18, 'CHF', 'CHF - Swiss Francs', 'CHF'),
	(19, 'CHFA', 'CHF - Swiss Francssss', 'CHFA');

INSERT IGNORE INTO `goStores_Vista_helps` (`id`, `title`, `content`, `type`, `order`) VALUES
	(1, 'Home Page', '<ul>\r\n    <li><span class="rvts10">The List of categories will be displayed on the left side with the option to navigate to subcategories and the related products.</span></li>\r\n    <li>A list of featured products and their thumbnails are displayed with a &lsquo;view more&rsquo; button for the combined products. The &lsquo;Add to cart&rsquo; button is for products without combinations</li>\r\n    <li>If the user logged in is a whole sale user then the whole sale price of the products will be shown otherwise the retail price will be shown.</li>\r\n    <li>A list of 5 new products and 5 top rated items appear on the right side of the page with a link to the details page.</li>\r\n    <li>A user can search for any product by entering the keyword in the &lsquo;search box&rsquo; provided in the top right of the page. Enter the keyword, and then select &lsquo;Search&rsquo; and you will see a search results page. From there, make your selection.\r\n    <meta content="text/html; charset=utf-8" http-equiv="CONTENT-TYPE" />\r\n    <meta content="OpenOffice.org 3.1  (Win32)" name="GENERATOR" /><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style></li>\r\n</ul>\r\n<p><br />\r\n&nbsp;</p>', 'U', 0),
	(2, 'Log in', '<ul>\r\n    <li>\r\n    <meta content="text/html; charset=utf-8" http-equiv="CONTENT-TYPE" />\r\n    <meta content="OpenOffice.org 3.1  (Win32)" name="GENERATOR" /><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	--></style>A user can log in to the website using the log in link at the top of every page.</li>\r\n    <li>The user will then be asked to enter their user name and password.</li>\r\n    <li>The user can subscribe for Newsletters if needed.</li>\r\n    <li>The user will be registered as a Retail user by default.</li>\r\n    <li>When finished, the user will select the &lsquo;Log In&rsquo; button to enter the website.</li>\r\n</ul>', 'U', 0),
	(3, 'Sign Up', '<ul>\r\n    <li>\r\n    <meta http-equiv="CONTENT-TYPE" content="text/html;\r\n    charset=utf-8">\r\n    <meta name="GENERATOR" content="OpenOffice.org 3.1\r\n    (Win32)">The user can sign up with the store by selecting the &lsquo;Sign Up&rsquo; link at the top of every page.          </meta>\r\n    </meta>\r\n    </li>\r\n    <li>In the sign up page, the user must enter their user name, password, re enter the password, and add an email address.</li>\r\n    <li>The user name must be unique and all fields are mandatory. Passwords are stored in the database in an encrypted format.</li>\r\n</ul>', 'U', 0),
	(4, 'Forgot password', '<ul>\r\n    <li><span class="rvts10">The login&nbsp; page will have a link to forgot password  page.</span></li>\r\n    <li><span class="rvts10">A user can reset his/her password from the forgot  password page.</span></li>\r\n    <li>If the user provides a valid user name and email address, the store will reset the password and then email the new password to the user.</li>\r\n</ul>\r\n<p>&nbsp;</p>', 'U', 0),
	(5, 'My Account', '<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li class="rvps2"><span class="rvts11">A&nbsp; My Account page link will be shown on the&nbsp; the top of every page for a logged in User.</span></li>\r\n    <li class="rvps2"><span class="rvts11">The My Account page will have links to&nbsp; </span><span class="rvts13">My Profile</span><span class="rvts11">,</span><a class="rvts13" href="file:///C:/Documents%20and%20Settings/Administrator/My%20Documents/Downloads/changes/fwvistacartedits/vistacartuserhelp/vistacartuserhelp/files/CartPage.html">My Cart</a><span class="rvts11">,</span><span class="rvts13"> My Orders</span><span class="rvts11">, My Shipping Address and My Billing Address pages.</span><span class="rvts11"><br />\r\n    </span>&nbsp;</li>\r\n</ul>\r\n<p class="rvps2" style="text-align: left"><strong><span class="rvts12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><span class="rvts12"><u><strong>My Profile</strong></u><br />\r\n</span></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">In this page,the user can edit&nbsp; his email address/password .</span></li>\r\n    <li><span class="rvts11">A user can view the items that has been added to the cart.</span></li>\r\n    <li><span class="rvts11">The user can remove any added item or update the quantity of a particular item.</span></li>\r\n    <li><span class="rvts11">The user can enter promo codes to get a discount.</span></li>\r\n    <li><span class="rvts11">The&nbsp; cart can contain either Digital or Non Digital products at a time.</span></li>\r\n    <li><span class="rvts11">The user can continue adding products to the cart by clicking on the Continue Shopping button.</span></li>\r\n    <li><span class="rvts11">The user can checkout by clicking on the checkout button.</span><span class="rvts11"><br />\r\n    </span></li>\r\n</ul>\r\n<p><strong><span class="rvts12">&nbsp;&nbsp;</span></strong><span class="rvts12">&nbsp;&nbsp;&nbsp;&nbsp;<strong> </strong><u><strong>My Orders</strong></u><br />\r\n</span></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">In this page, the user can view all their orders.</span><span class="rvts11"><br />\r\n    </span></li>\r\n</ul>\r\n<p class="rvps2"><strong><span class="rvts12">&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; </span></strong><u><strong><span class="rvts12">My Billing Address</span></strong></u><span class="rvts12"><br />\r\n</span></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">In this page,the user can add/edit the Billing address Information . </span><u><strong><span class="rvts12"><br />\r\n    </span></strong></u></li>\r\n</ul>\r\n<p class="rvps2"><strong><span class="rvts12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><u><strong><span class="rvts12">My Shipping Address</span></strong></u><span class="rvts12"><br />\r\n</span></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">In this page,the user can add/edit the Shipping address Information . </span></li>\r\n</ul>\r\n<p class="rvps2"><strong><span class="rvts12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><u><strong><span class="rvts12">My Refund Request</span></strong></u></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">In this page,the user can&nbsp;make request for&nbsp;refund for the products that he/she has purchased&nbsp;&nbsp;. </span></li>\r\n</ul>\r\n<p class="rvps2"><strong><span class="rvts12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><u><strong><span class="rvts12">My Giftcards</span></strong></u><span class="rvts12"><br />\r\n</span></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">In this page,the user can&nbsp;view the giftcards and the&nbsp;balance amount of&nbsp;each giftcard that he/she has purchased&nbsp;. </span></li>\r\n</ul>\r\n<p class="rvps2"><strong><span class="rvts12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><u><strong><span class="rvts12">My Giftcard Usage</span></strong></u></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">In this page,the user can view the list of giftcards&nbsp; that he has used for&nbsp;the product purchases from the website along with the amount used for each purchase.</span>&nbsp;</li>\r\n</ul>\r\n<p><strong>&nbsp;&nbsp;&nbsp;&nbsp; <u>Unsubscribe Newsletter</u></strong><span class="rvts12"><br />\r\n</span></p>\r\n<ul style="list-style-position: outside; text-indent: 0px; margin-left: 24px">\r\n    <li><span class="rvts11">This link allows the user to subscribe/unsubscribe newsletter.</span>&nbsp;</li>\r\n</ul>\r\n<p>&nbsp;</p>\r\n<p class="rvps2"><span class="rvts12"><br />\r\n</span></p>', 'U', 0),
	(6, 'Product Details Page', '<ul style="list-style-position: outside; text-indent: 0px;">\r\n    <li class="rvps2"><span class="rvts10">The details of each product such as the name and description are displayed here.</span></li>\r\n    <li class="rvps2"><span class="rvts10">The images of the product appear in an image slider with a &lsquo;next&rsquo; and &lsquo;previous&rsquo; button to help navigate.</span></li>\r\n    <li class="rvps2"><span class="rvts10">The current rating and price of the product are shown under the &lsquo;Product Image Slider&rsquo;.</span></li>\r\n    <li class="rvps2">If the logged in user is a wholesale user then both wholesale and retail price of products will be shown.</li>\r\n    <li class="rvps2"><span class="rvts10">The product is rated by selecting the stars, so viewers can determine what the best selection will be.</span></li>\r\n    <li class="rvps2"><span class="rvts10">Various combinations of the product appear when the user selects the desired option from the select box. The image, SKU number, and price appear here with an &lsquo;Add to Cart&rsquo; button. <br />\r\n    </span></li>\r\n    <li class="rvps2"><span class="rvts10">Any user can view/post feedback on a product by selecting the &lsquo;post&rsquo; and &lsquo;view&rsquo; feedback links on the bottom. To post, the customer must purchase the same product at least once.<br />\r\n    </span></li>\r\n</ul>\r\n<p>&nbsp;</p>', 'U', 0),
	(7, 'Cart Page', '<ul style="text-indent: 0px;list-style-position: outside;">\r\n    <li class="rvps2"><span class="rvts10">A user can view the items that are added to the cart.<br />\r\n    </span></li>\r\n    <li class="rvps2"><span class="rvts10">The user can remove any added  item or update the quantity of a particular item.</span></li>\r\n    <li class="rvps2"><span class="rvts10">If you have a promo code, you can enter it here.</span></li>\r\n    <li class="rvps2"><span class="rvts10">The cart can contain all physical products or all downloadable products here.</span></li>\r\n    <li class="rvps2"><span class="rvts10">The user can continue adding  products to the cart by clicking on the Continue Shopping button.</span></li>\r\n    <li class="rvps2"><span class="rvts10">Select the &lsquo;Check out&rsquo; button when you are finished adding products.</span></li>\r\n</ul>', 'U', 0),
	(8, 'Checkout', '<p><span class="rvts10">When you select the &lsquo;Check out from Carts Page&rsquo;, if you aren&rsquo;t logged in, the system will allow you to do so if you register to the store, or purchase as a guest. </span><span class="rvts10"><br />\r\n</span></p>\r\n<ul style="text-indent: 0px;list-style-position: outside;">\r\n    <li class="rvps2"><span class="rvts10">When you select the &lsquo;Check out&rsquo; button on the carts page, the user will then have two options. You can log in by registering to the store, or purchase the product as a guest. <br />\r\n    </span></li>\r\n    <li class="rvps2"><span class="rvts10">When you select the &lsquo;Check out as a guest&rsquo; button a link will automatically create your log in credentials as a &lsquo;guest user&rsquo;. From here, you have full access to the store. <br />\r\n    </span></li>\r\n    <li><span class="rvts10">The guest user must enter the correct shipping and billing information. Just select the &lsquo;Billing email address&rsquo; text box.&nbsp; The new log in details of the guest user are then sent to that email address.</span></li>\r\n</ul>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>', 'U', 0),
	(9, 'Billing/ Shipping Address', '<p>\r\n<meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8">\r\n<meta name="GENERATOR" content="OpenOffice.org 3.1  (Win32)"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>    </meta>\r\n</meta>\r\nDuring the check out process, the system will ask for the user&rsquo;s billing &amp; shipping address for non digital products and billing address for digital products. If the user has already entered these addresses, then the&nbsp;user can edit them here. For a non digital product, the user can select a shipping option. After they select the &lsquo;Save Addresses&rsquo; button, the store will lead the user to the shipping address page and show the rate available.&nbsp;</p>', 'U', 0),
	(10, 'Payment Selection', '<p>The store will show a &lsquo;Payment Selection&rsquo; page that shows all of the payment options available. Please enter the payment information as directed. The store will send you an email with all the details.</p>', 'U', 0),
	(11, 'Search For a product', '<ul>\r\n    <li>The store supports category and keyword searches.</li>\r\n    <li>For category searches- the user can navigate through the category. When they select a leaf level category, the website will show all products under that category.</li>\r\n    <li>For keyword searches- the user has to enter the item in the search text box at the top of the home page. When they select the &lsquo;Search&rsquo; button, the user will get their search results. </li>\r\n</ul>', 'U', 0),
	(12, 'View your orders', '<p>In order to see the orders placed by a customer, they can select &lsquo;My account page&rsquo;-&gt; My Orders links. This page will list all the orders. To view other details, the customer has to select the &lsquo;order number&rsquo;. From the order details page, the customer can change the order status to &lsquo;Order Accepted&rsquo;.</p>', 'U', 0),
	(13, 'Settings', '<p>In this page, the administrator can manage the website configurations. It consists of 4 Submenus:</p>\r\n\r\n<p><u><strong>General</strong></u></p>\r\n\r\n<p>In the General Settings Page, the administrator can change the Name, email, logo, template, page title, Meta tag description, URL store location, and the number of images per products.<br />\r\nThe administrator can enable/disable the Gift Coupons (Promo code), rating on products by customers, feedback posts on products, and send orders to administrator via fax.<br />\r\nThey can also give a time limit to customers for downloading the digital products they purchase from the store.&nbsp;</p>\r\n\r\n<p><strong><u>Shipping</u></strong></p>\r\n\r\n<p>The store supports five flat rate shipping and shipping API&rsquo;S: UPS, USPS, FEDEX, Canada Post, and Australia Post. Use flat rate shipping if you don&rsquo;t want to calculate the real time shipping costs using the shipping API&rsquo;s. For flat rate shipping, admin can set the shipping charge for the first item and a separate charge for any additional items. The administrator can enable/disable all the shipping methods if they want.They can also give the shipping service name.In shipping tab,the administrator must enter the shipping orirgin postal code and country.</p>\r\n\r\n<p>&nbsp;<strong><u>Payment</u></strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>In the payment Page, the administrator can enable/disable the payment gateways.&nbsp; They can also select the currency for all transactions. The store supports offline credit card payment, and payment gateways like: PayPal, Authorize.net, Your Pay, World Pay, Blue Pay and Google Checkout.<br />\r\n&nbsp;If offline payment is selected the credit card information is not verified online, so please verify and charge using POS before shipping. This offline payment is a good solution for physical retail stores. If you enable an offline credit card payment, the site will not receive any payment transactions from your customers; it will send the credit card information in an email to the site administrator.<br />\r\nIt is necessary to enable at least one payment method&nbsp; for your site.</p>\r\n\r\n<p><strong><u>Tax</u></strong></p>\r\n\r\n<p>In the tax settings page, the administrator can manage the tax settings in the website. This page has two tabs: General, and Tax Rates</p>\r\n\r\n<p>In the General settings tab- the administrator can opt for no tax to all customers, a fixed tax rate, or tax based on any country/state. The administrator can also choose the base to categorize the taxes as subtotal or subtotal + shipping. The administrator can use taxable address as a billing address or shipping address.</p>\r\n\r\n<p>If the administrator opts fixed tax rates, they can create a tax name.&nbsp;</p>\r\n\r\n<p>If the administrator wants a specific tax based on a state and/or country, the tax rate tab is enabled.</p>\r\n\r\n<p>In this tab, the administrator can add/edit/delete any/tax rates for states or countries. In most jurisdictions you collect taxes for states with nexus, based on the shipping address. For example: if you have a store in the state of California, you have to collect taxes from all customers in California. Please obtain legal advice for your local tax laws.</p>\r\n\r\n<p>&nbsp;</p>\r\n', 'A', 1),
	(17, 'Import Product & Images', '<p>&nbsp;</p>\r\n\r\n<p>The shopping cart allows you to import products in bulk using .csv file (comma separated values) and .zip format(s).</p>\r\n\r\n<p>To import products- you must upload the csv file to the site using the sample csv format provided and match the data fields. When you select the &lsquo;save&rsquo; button all of your products will import into the website</p>\r\n\r\n<p>To import product images- you must&nbsp;create a zip files with&nbsp;the images you want to upload for a particular product.The name of the zip file should be same as that of the product name.</p>\r\n\r\n<p>&nbsp;</p>\r\n', 'A', 7),
	(14, 'Custom Variables', '<p style="margin-bottom: 0in;">In the custom fields and values tab, the administrator can manage all product variables and their values. For example: if your site sells clothes, you may have a shirt in your product list. The shirt can have different variants like size (XL,XXL,etc) color (blue, red), and fabric (cotton, polyester).</p>\r\n<p style="margin-bottom: 0in;">For the site you can add The Size, Color, and Fabric as custom fields. The XL,XXL, Blue, Red, and Cotton, Polyester, are the custom field values.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>', 'A', 4),
	(15, 'Categories', '<p>\r\n<meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8">\r\n<title></title>\r\n<meta name="GENERATOR" content="OpenOffice.org 3.1  (Win32)"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>     </meta>\r\n</meta>\r\n</p>\r\n<p style="margin-bottom: 0in;">The store allows you to create any number of levels of categories on your site. You can add products to leaf level categories only. When adding categories you can assign custom fields and values only applicable to that category.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>', 'A', 5),
	(16, 'Products', '<p style="margin-left: 200px;">\r\n<meta content="text/html; charset=utf-8" http-equiv="CONTENT-TYPE">\r\n<title></title>\r\n<meta content="OpenOffice.org 3.1  (Win32)" name="GENERATOR"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>  </meta>\r\n</meta>\r\n</p>\r\n<p>&nbsp;In the products tab, you can add/edit/delete products.</p>\r\n<p style="margin-bottom: 0in;">To add a product- you must first select a category, enter the product name, description, price, weight, and then select physical or downloadable, set feature/not feature, browse images, select the SKU number, additional amount, and re order level for each custom value combination.</p>\r\n<p style="margin-bottom: 0in;">For custom value combinations- you can upload the product image</p>\r\n<p style="margin-bottom: 0in;">Examples: if you upload a t-shirt, it might be red,XL, cotton, Blue, XXL, cotton, and red XXL, cotton. Each one will have a different image, stock, re order number, and batch number. Some combinations might have an additional price. That can also be managed here.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>\r\n<p>&nbsp;</p>', 'A', 6),
	(18, 'Feedback', '<p style="margin-bottom: 0in;">In the feedback page, the administrator can view customer feedback about the website and the products. Only customers who purchased a product at least once are allowed to give feedback on that product.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>\r\n<p>&nbsp;</p>', 'A', 8),
	(19, 'Users', '<p>\r\n<meta content="text/html; charset=utf-8" http-equiv="CONTENT-TYPE">\r\n<meta content="OpenOffice.org 3.1  (Win32)" name="GENERATOR"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>  </meta>\r\n</meta>\r\nIn the user page, the administrator can view, edit, and delete customers registered with the site.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>\r\n<p>&nbsp;</p>', 'A', 9),
	(20, 'Orders', '<p>\r\n<meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8">\r\n<title></title>\r\n<meta name="GENERATOR" content="OpenOffice.org 3.1  (Win32)"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>     </meta>\r\n</meta>\r\nIn the orders page, the administrator can view the details of the orders. They can change the order status and add comments for internal use.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>', 'A', 15),
	(21, 'Website Contents', '<p>\r\n<meta content="text/html; charset=utf-8" http-equiv="CONTENT-TYPE">\r\n<title></title>\r\n<meta content="OpenOffice.org 3.1  (Win32)" name="GENERATOR"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>       </meta>\r\n</meta>\r\nIn the website content page, the administrator can edit content for the About Us section, the FAQ section, and the Terms and Conditions pages.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>', 'A', 2),
	(22, 'Email Templates', '<p>\r\n<meta content="text/html; charset=utf-8" http-equiv="CONTENT-TYPE">\r\n<title></title>\r\n<meta content="OpenOffice.org 3.1  (Win32)" name="GENERATOR"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>   </meta>\r\n</meta>\r\nIn the email templates page, the administrator can view and edit the email templates for emails to send from the website.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>\r\n<p>&nbsp;</p>', 'A', 3),
	(24, 'Promo Codes', '<p>\r\n<meta content="text/html; charset=utf-8" http-equiv="CONTENT-TYPE">\r\n<title></title>\r\n<meta content="OpenOffice.org 3.1  (Win32)" name="GENERATOR"><style type="text/css">\r\n	<!--\r\n		@page { margin: 0.79in }\r\n		P { margin-bottom: 0.08in }\r\n	-->\r\n	</style>       </meta>\r\n</meta>\r\nIn the promo codes tab, the administrators can add/edit/delete promo codes.</p>\r\n<p style="margin-bottom: 0in;">For the promo codes, the administrator inputs a promo code, discount type as a fixed amount or rate, discount value, start and end dates, the minimum amount required, and the description of the promo code.</p>\r\n<p style="margin-bottom: 0in;">&nbsp;</p>', 'A', 10),
	(25, 'Reports', '<p>Product reports, sales reports,user activity reports, user reports, and promo code reports are the reports generated in the store. All of the reports can be be exported in. CSV and .XLS file formats.</p>\r\n<p><b><u> </u></b></p>\r\n<p><b><u><span id="1285830993889S" style="display: none">&nbsp;</span>Product Report</u></b></p>\r\n<p><b><u> </u></b></p>\r\n<p>&nbsp;</p>\r\n<p>In the products report, the website will show the Product name,Stock available, and the Total revenue.</p>\r\n<p><b><u> </u></b></p>\r\n<p><b><u>Sales Report</u></b></p>\r\n<p><b><u> </u></b></p>\r\n<p>&nbsp;</p>\r\n<p>In the sales report,the website will show the Order number,sales date, purchased user, Order status, promo code used to purchase, discount given and the total price.</p>\r\n<p><b><u> </u></b></p>\r\n<p><b><u>User Report</u></b></p>\r\n<p><b><u> </u></b></p>\r\n<p>&nbsp;</p>\r\n<p>In user reports , the website will show the details like username, Name of the customer,Email address, registration date in the website, address and other customer details.</p>\r\n<p><b><u> </u></b></p>\r\n<p><b><u>User Activity Report</u></b></p>\r\n<p><b><u> </u></b></p>\r\n<p>&nbsp;</p>\r\n<p>In user activity reports , the website will show the details like Order date,Order status,Shipping address,Billing address,Total of all the purchases made by a particular customer.</p>\r\n<p><b><u> </u></b></p>\r\n<p><b><u>Promo Code Report</u></b></p>\r\n<p><b><u> </u></b></p>\r\n<p>&nbsp;</p>\r\n<p>In promo code report, the system will show the details of the promo codes used by the customers.This details include code, Order number,Order date,Order status and discount value.</p>', 'A', 16),
	(26, 'Newsletter Subscribers', '<p>In this page, the user can view the list of the users subscribed for Newsletters,add new newsletter users,activiate or deactivate the users for newsletter subscription.</p>', 'A', 14),
	(27, 'Newsletters', '<p>In this page, the administrator can add/edit Newsletters,Send newsletter to retail users or wholesale users or both.</p>', 'A', 13),
	(28, 'Giftcards', '<p>In this page administrator can add/edit giftcards.These gift cards will be displayed along with the products for purchase&nbsp;on user side.</p>', 'A', 11),
	(29, 'Giftcard Users', '<p>In this page,the administrator can view the list of users who has used giftcards for purchases.It shows details such as Card name,Used card code,date,Amount used.</p>', 'A', 12),
	(34, 'Sample Content', '<p>Sample Content</p>\r\n', 'A', 0);

INSERT IGNORE INTO `goStores_Vista_homelayouts` (`id`, `prod_type`, `section`, `status`, `ordering`) VALUES
	(1, 'featured', 'right', 'Y', 2),
	(2, 'latest', 'right', 'Y', 1),
	(4, 'onsale', 'right', 'Y', 3);

INSERT IGNORE INTO `goStores_Vista_order_statuses` (`id`, `name`) VALUES
	(1, 'Unprocessed'),
	(2, 'Processed'),
	(3, 'Failed'),
	(4, 'Pending'),
	(5, 'Manually Processed'),
	(6, 'Canceled'),
	(7, 'Shipped'),
	(8, 'Completed'),
	(9, 'Partial Shipped'),
	(10, 'Backordered');

INSERT IGNORE INTO `goStores_Vista_refundoptions` (`id`, `title`) VALUES
	(1, 'Refund'),
	(2, 'Repair'),
	(3, 'Replacement');

INSERT IGNORE INTO `goStores_Vista_refundreasons` (`id`, `title`) VALUES
	(1, 'Can not make it work'),
	(2, 'Damaged during shipping'),
	(3, 'Dead on arrival'),
	(4, 'Manufacturer defect'),
	(5, 'Out of Warranty'),
	(6, 'Wrong item ordered'),
	(7, 'Wrong description online'),
	(8, 'Wrong item delivered');

INSERT IGNORE INTO `goStores_Vista_refundstatuses` (`id`, `title`) VALUES
	(1, 'Waiting for review'),
	(2, 'Reviewed'),
	(3, 'Rejected'),
	(4, 'Closed'),
	(5, 'Approved');

INSERT IGNORE INTO `goStores_Vista_settings` (`fieldname`, `value`) VALUES
	('admin_email', ''),
	('site_name', 'My Account'),
	('payment_method', 'paypal-*-twocheckout-*-paypalpro-*-paypalflow-*-paypallink-*-paypaladvanced-*-ogone-*-braintree-*-moneybrokers-*-paypal_express-*-authorize-*-googlechk'),
	('paypal_email', ''),
	('paypal_idtoken', ''),
	('paypal_testmode', 'Y'),
	('authorize_loginid', ''),
	('authorize_transactionkey', ''),
	('authorize_email', ''),
	('authorize_password', ''),
	('authorize_testmode', 'Y'),
	('shipping_origin_country', ''),
	('shipping_origin_zip', ''),
	('sitebasefolder', ''),
	('smtpHostNames', ''),
	('smtpUserName', ''),
	('smtpPassword', ''),
	('smtpPort', '587'),
	('meta_description', 'My Store Using shopping cart , You can create a virtual mall like aggregator ecommerce business wit'),
	('meta_keywords', 'my store arms,boutique,shopping cart, shopping cart software, shopping carts, ecommerce software, ecommerce solution,  PHP'),
	('shipping_require', 'N'),
	('currency', 'USD'),
	('style', 'Garments'),
	('page_title', 'My Store'),
	('no_tax_home', 'Y'),
	('home_state', ''),
	('tax_foreign', '0'),
	('digitalproduct_download_limit', '48'),
	('shipping_require_usps', 'N'),
	('shipping_require_fedex', 'N'),
	('shipping_require_canada', 'N'),
	('shipping_require_australia', 'N'),
	('USPS_Username', ''),
	('fedexaccno', ''),
	('fedexmeterno', ''),
	('canadamerchantid', ''),
	('enable_twitter', 'Y'),
	('worldpay_inst_Id', ''),
	('worldpay_email', ''),
	('worldpay_transact_method', 'C'),
	('google_merchantId', ''),
	('google_merchantkey', ''),
	('google_testmode', 'Yes'),
	('yourpay_testmod', 'YES'),
	('yourpay_storeid', ''),
	('yourpay_certificate_file', ''),
	('allow_rating', 'Y'),
	('allow_product_feedback', 'Y'),
	('flat_shipping_first', '2'),
	('flat_shipping_additional', '1'),
	('tax_option', 'statetax'),
	('fixedtax_name', 'Iinfini Tax'),
	('fixedtax_rate', '15'),
	('taxable_address', 'shipping'),
	('taxto', 'gtotal'),
	('product_images', '6'),
	('flat_ship_name', 'Flat Rate Shipping1'),
	('secflat_shipping_first', '3'),
	('secflat_shipping_additional', '2'),
	('secflat_ship_name', 'Flat Rate Shipping2'),
	('thirdflat_shipping_first', '4'),
	('thirdflat_shipping_additional', '3'),
	('thirdflat_ship_name', 'Flat Rate Shipping3'),
	('forthflat_shipping_first', '3'),
	('forthflat_shipping_additional', '2'),
	('forthflat_ship_name', 'Flat Rate Shipping4'),
	('fflat_shipping_require', 'N'),
	('sflat_shipping_require', 'N'),
	('tflat_shipping_require', 'N'),
	('foflat_shipping_require', 'N'),
	('allow_giftcoupon', 'Y'),
	('allow_fax', 'Y'),
	('fax_email', ''),
	('fax_number', ''),
	('guestnumber', '23'),
	('offline_creditpay', 'Y'),
	('allow_rma', 'Y'),
	('allow_giftcard', 'Y'),
	('offline_creditpay', 'Y'),
	('allow_rma', 'Y'),
	('fedexshipaccno', ''),
	('fedexbillaccno', ''),
	('fedexdutyaccno', ''),
	('fedexkey', ''),
	('fedexpaswd', ''),
	('items_perpage', '50'),
	('allow_fedexlabel', 'Y'),
	('shipping_origin_state', 'AK'),
	('bp_account', '100042832485'),
	('bp_secret', ''),
	('bp_testmode', 'Y'),
	(' vLicenceKey', ''),
	('vLicenceKey', '140CSI270101000011399221112STP'),
	('enable_googleanalytics', 'N'),
	('googleanalytic_id', ''),
	('admin_blog_settings', 'N'),
	('enable_paypal_express', 'N'),
	('paypal_express_password', ''),
	('twocheckout_testmode', 'Y'),
	('twoco_vendorId', '1877160'),
	('paypal_express_username', ''),
	('paypal_express_signature', ''),
	('moneybookers_emailId', ''),
	('paypalpro_username', ''),
	('paypal_express_testmode', 'N'),
	('paypalpro_password', ''),
	('paypalpro_signature', ''),
	('paypalpro_testmode', 'Y'),
	('pay_paypalpro', ''),
	('paypalflow_partnerid', ''),
	('paypalflow_vendorid', ''),
	('paypalflow_password', ''),
	('paypalflow_testmode', 'Y'),
	('paypallink_partnerid', ''),
	('paypallink_vendorid', ''),
	('paypallink_testmode', 'Y'),
	('user_credit', '1.00'),
	('worldpay_merchantcode', ''),
	('worldpay_password', ''),
	('worldpay_testmode', '100'),
	('enable_facebook', 'Y'),
	('facebook_url', 'http://www.facebook.com/mystore'),
	('twitter_url', 'http://www.twitter.com/mystore'),
	('ogone_PSPID', ''),
	('ogone_passphrase', ''),
	('ogone_testmode', 'Y'),
	('shipping_origin_phone', ''),
	('shipping_origin_street', ''),
	('shipping_origin_city', ''),
	('streamsendLoginID', ''),
	('streamsendKey', ''),
	('streamsendListID', '1'),
	('streamsendEnable', 'N'),
	('paypal_advancedPWD', ''),
	('paypal_advancedUSER', ''),
	('paypal_advancedVENDOR', ''),
	('paypal_advancedPARTNER', ''),
	('paypal_advancedtestmode', 'Y'),
	('allow_uspslabel', 'N'),
	('braintree_merchantId', ''),
	('braintree_publicKey', ''),
	('braintree_privateKey', ''),
	('braintree_testmode', 'Y'),
	('abdncart_reminder', '2'),
	('store_id', '40008b9a5380fcacce3976bf7c08af5b'),
	('shipping_rate_type', 'free'),
	('enable_translator', 'Y'),
	('allow_upsell', 'N'),
	('apikey', ''),
	('taxation_type', '1'),
	('fixed_tax_rate', '0'),
	('cc_surcharge', ''),
	('in_store_pickup', '0'),
	('firearms_in_store_pickup', '0'),
	('firearms_fee', '0'),
	('general_shipping_fee', '0'),
	('markup_defaultrate', '0'),
	('bluedog_userid', ''),
	('bluedog_api_key', ''),
	('bluedog_password', ''),
	('bluedog_testmode', 'Y'),
	('customer_receipt', 'Your item will be shipped soon'),
	('ship_service_name', 'Flat rate shipping'),
	('contact_email', ''),
	('contact_phone', ''),
	('about_description', 'Precision Arsenal shares your passion for long range precision, cowboy action shooting, 3 gun competition, gun collecting, hunting, and self defense. We are also proud to serve those who defend our 2nd Amendment rights. We update specials often and are constantly adding to our inventory of pistols, handguns, rifles, shotguns, ammunition, and accessories. Stay up to date by following us on Instagram, Facebook, and Twitter. \r\nRespectfully, \r\nThe Precision Arsenal Team.'),
	('incl_ship_charge_for_tax', '0'),
	('enable_local_pick_up', 'N'),
	('site_email', ''),
	('ffl_file', ''),
	('ffl_id', ''),
	('dynamic_tax_rate', '0'),
	('store_address', ''),
	('subscribed_planid', '2'),
	('subscribed_templateid', '4'),
	('appearance_colorscheme', ''),
	('appearance_backdrop', ''),
	('appearance_layout', ''),
	('appearance_bgimage', ' '),
	('appearance_bgfit', ''),
	('site_logo', 'SiteLogo.png'),
	('inventory_plugin_status', '0'),
	('inventory_form_fill_status', '0'),
	('invsrc_authtoken', ''),
	('main_site', ''),
	('super_admin_email', ''),
	('stripe_webhook_secret_key', ''),
	('stripe_test_mode', 'Y'),
	('stripe_sandbox_secretkey', ''),
	('stripe_sandbox_publishkey', ''),
	('stripe_live_webhook_secret_key', ''),
	('stripe_live_secretkey', ''),
	('stripe_live_publishkey', ''),
	('stripe_enable', 'Y');

INSERT IGNORE INTO `goStores_Vista_shipping_rates` (`id`, `ship_rate_type`, `ship_rate_name`, `free_ship_type`, `min_value`, `max_value`, `currency`, `weight_type`, `ship_rate`, `ship_other_rate`) VALUES
	(1, 'free', 'Free shipping', 'order_price', 0.00, 100.00, '$', '', 0.00, 0.00);

INSERT IGNORE INTO `goStores_Vista_statecodes` (`id`, `code`, `name`, `country_id`) VALUES
	(1, 'AK', 'Alaska', '223'),
	(2, 'AL', 'Alabama', '223'),
	(3, 'AR', 'Arkansas', '223'),
	(4, 'AS', 'American Samoa', '223'),
	(5, 'AZ', 'Arizona', '223'),
	(6, 'CA', 'California', '223'),
	(7, 'CO', 'Colorado', '223'),
	(8, 'CT', 'Connecticut', '223'),
	(9, 'DC', 'D.C.', '223'),
	(10, 'DE', 'Delaware', '223'),
	(11, 'FL', 'Florida', '223'),
	(12, 'FM', 'Micronesia', '223'),
	(13, 'GA', 'Georgia', '223'),
	(14, 'GU', 'Guam', '223'),
	(15, 'HI', 'Hawaii', '223'),
	(16, 'IA', 'Iowa', '223'),
	(17, 'ID', 'Idaho', '223'),
	(18, 'IL', 'Illinois', '223'),
	(19, 'IN', 'Indiana', '223'),
	(20, 'KS', 'Kansas', '223'),
	(21, 'KY', 'Kentucky', '223'),
	(22, 'LA', 'Louisiana', '223'),
	(23, 'MA', 'Massachusetts', '223'),
	(24, 'MD', 'Maryland', '223'),
	(25, 'ME', 'Maine', '223'),
	(26, 'MH', 'Marshall Islands', '223'),
	(27, 'MI', 'Michigan', '223'),
	(28, 'MN', 'Minnesota', '223'),
	(29, 'MO', 'Missouri', '223'),
	(30, 'MP', 'Marianas', '223'),
	(31, 'MS', 'Mississippi', '223'),
	(32, 'MT', 'Montana', '223'),
	(33, 'NC', 'North Carolina', '223'),
	(34, 'ND', 'North Dakota', '223'),
	(35, 'NE', 'Nebraska', '223'),
	(36, 'NH', 'New Hampshire', '223'),
	(37, 'NJ', 'New Jersey', '223'),
	(38, 'NM', 'New Mexico', '223'),
	(39, 'NV', 'Nevada', '223'),
	(40, 'NY', 'New York', '223'),
	(41, 'OH', 'Ohio', '223'),
	(42, 'OK', 'Oklahoma', '223'),
	(43, 'OR', 'Oregon', '223'),
	(44, 'PA', 'Pennsylvania', '223'),
	(45, 'PR', 'Puerto Rico', '223'),
	(46, 'PW', 'Palau', '223'),
	(47, 'RI', 'Rhode Island', '223'),
	(48, 'SC', 'South Carolina', '223'),
	(49, 'SD', 'South Dakota', '223'),
	(50, 'TN', 'Tennessee', '223'),
	(51, 'TX', 'Texas', '223'),
	(52, 'UT', 'Utah', '223'),
	(53, 'VA', 'Virginia', '223'),
	(54, 'VI', 'Virgin Islands', '223'),
	(55, 'VT', 'Vermont', '223'),
	(56, 'WA', 'Washington', '223'),
	(57, 'WI', 'Wisconsin', '223'),
	(58, 'WV', 'West Virginia', '223'),
	(59, 'WY', 'Wyoming', '223'),
	(60, 'AA', 'Military Americas', '223'),
	(61, 'AE', 'Military Europe)ME)Canada', '223'),
	(62, 'AP', 'Military Pacific', '223');

INSERT IGNORE INTO `goStores_Vista_states` (`id`, `code`, `name`, `country_id`, `tax_rate`, `tax_name`) VALUES
	(1, 'AK', 'Alaska', 'US', 20.00, 'Sales Tax'),
	(2, 'AL', 'Alabama', 'US', 0.00, ''),
	(3, 'AR', 'Arkansas', 'US', 0.00, ''),
	(4, 'AS', 'American Samoa', 'US', 0.00, ''),
	(5, 'AZ', 'Arizona', 'US', 0.00, ''),
	(6, 'CA', 'California', 'US', 10.00, ''),
	(7, 'CO', 'Colorado', 'US', 0.00, ''),
	(8, 'CT', 'Connecticut', 'US', 0.00, ''),
	(9, 'DC', 'D.C.', 'US', 0.00, ''),
	(10, 'DE', 'Delaware', 'US', 0.00, ''),
	(11, 'FL', 'Florida', 'US', 0.00, ''),
	(12, 'FM', 'Micronesia', 'US', 0.00, ''),
	(13, 'GA', 'Georgia', 'US', 0.00, ''),
	(14, 'GU', 'Guam', 'US', 0.00, ''),
	(15, 'HI', 'Hawaii', 'US', 0.00, ''),
	(16, 'IA', 'Iowa', 'US', 0.00, ''),
	(17, 'ID', 'Idaho', 'US', 0.00, ''),
	(18, 'IL', 'Illinois', 'US', 0.00, ''),
	(19, 'IN', 'Indiana', 'US', 0.00, ''),
	(20, 'KS', 'Kansas', 'US', 0.00, ''),
	(21, 'KY', 'Kentucky', 'US', 0.00, ''),
	(22, 'LA', 'Louisiana', 'US', 0.00, ''),
	(23, 'MA', 'Massachetts', 'US', 0.00, ''),
	(24, 'MD', 'Maryland', 'US', 0.00, ''),
	(25, 'ME', 'Maine', 'US', 0.00, ''),
	(26, 'MH', 'Marshall Islands', 'US', 0.00, ''),
	(27, 'MI', 'Michigan', 'US', 0.00, ''),
	(28, 'MN', 'Minnesota', 'US', 0.00, ''),
	(29, 'MO', 'Missouri', 'US', 0.00, ''),
	(30, 'MP', 'Marianas', 'US', 0.00, ''),
	(31, 'MS', 'Mississippi', 'US', 0.00, ''),
	(32, 'MT', 'Montana', 'US', 0.00, ''),
	(33, 'NC', 'North Carolina', 'US', 0.00, ''),
	(34, 'ND', 'North Dakota', 'US', 0.00, ''),
	(35, 'NE', 'Nebraska', 'US', 0.00, ''),
	(36, 'NH', 'New Hampshire', 'US', 0.00, ''),
	(37, 'NJ', 'New Jersey', 'US', 0.00, ''),
	(38, 'NM', 'New Mexico', 'US', 0.00, ''),
	(39, 'NV', 'Nevada', 'US', 0.00, ''),
	(40, 'NY', 'New York', 'US', 0.00, ''),
	(41, 'OH', 'Ohio', 'US', 0.00, ''),
	(42, 'OK', 'Oklahoma', 'US', 15.00, 'Oklahoma tax'),
	(43, 'OR', 'Oregon', 'US', 0.00, ''),
	(44, 'PA', 'Pennsylvania', 'US', 0.00, ''),
	(45, 'PR', 'Puerto Rico', 'US', 0.00, ''),
	(46, 'PW', 'Palau', 'US', 0.00, ''),
	(47, 'RI', 'Rhode Island', 'US', 0.00, ''),
	(48, 'SC', 'South Carolina', 'US', 0.00, ''),
	(49, 'SD', 'South Dakota', 'US', 0.00, ''),
	(50, 'TN', 'Tennessee', 'US', 0.00, ''),
	(51, 'TX', 'Texas', 'US', 0.00, ''),
	(52, 'UT', 'Utah', 'US', 0.00, ''),
	(53, 'VA', 'Virginia', 'US', 0.00, ''),
	(54, 'VI', 'Virgin Islands', 'US', 0.00, ''),
	(55, 'VT', 'Vermont', 'US', 0.00, ''),
	(56, 'WA', 'Washington', 'US', 0.00, ''),
	(57, 'WI', 'Wisconsin', 'US', 0.00, ''),
	(58, 'WV', 'West Virginia', 'US', 0.00, ''),
	(59, 'WY', 'Wyoming', 'US', 0.00, ''),
	(60, 'AA', 'Military Americas', 'US', 0.00, ''),
	(61, 'AE', 'Military Europe)ME)Canada', 'US', 0.00, ''),
	(62, 'AP', 'Military Pacific', 'US', 0.00, ''),
	(65, 'KL', 'Kerala', 'IN', 2.00, 'Kerala Special Tax');

INSERT IGNORE INTO `goStores_Vista_tags` (`tag_id`, `tag_name`, `status`) VALUES
	(1, 'Cart', 1);

INSERT IGNORE INTO `goStores_Vista_templates` (`id`, `template_name`, `banner_resolution`, `ad_resolution`, `ad_count`, `status`) VALUES
	(1, 'atzshop', '2420x534', '500x300', 3, 1),
	(2, 'linea', '2420x534', '288x534', 4, 1),
	(3, 'rapidshop', '1900x550', '500x300', 3, 1),
	(4, 'autima', '1900x550', '555x402', 2, 1),
	(5, 'ruger', '1920x781', '500x300', 3, 1),
        (6, 'vistacart', '2420x534', '288x534', 3, 1);

INSERT IGNORE INTO `goStores_Vista_vendors` (`vendor_id`, `vendor_name`, `vendor_code`, `status`) VALUES
	(1, 'Iscripts Gostores', 'MRA', 1);
INSERT INTO `goStores_User` (`vUsername`, `vPassword`, `vFirstName`, `vLastName`, `dLastLogin`, `dLastUpdated`, `vEmail`, `vInvoiceEmail`, `vAddress`, `vCountry`, `vState`, `vCity`, `vZipcode`, `vPhoneNumber`, `vFax`, `vActivationKey`, `nStatus`, `nAffId`, `vAffType`, `nRefId`,`nShopperId`) VALUES ('James', '91017d590a69dc49807671a51f10ab7f', 'James', 'Smith', '2015-10-14 03:35:41', '2015-10-13 17:05:41', 'demouser@iscripts.com', 'demouser@iscripts.com', 'address', '', 'address', '', '12345', '32324333', '', 're508909bee8b26', '1', 0, '', 0, NULL);
INSERT INTO `goStores_Vista_users` (`uname`, `password`, `email`, `reg_date`, `usertype`, `reg_status`, `user_credit`) VALUES ('user', '1a1dc91c907325c69271ddf0c944bc72', 'user@kidscorner.com', '2010-10-15 12:20:52', 'retail', 'R', 0);
INSERT INTO `goStores_Vista_settings` (`fieldname`, `value`) VALUES ('product_count', '1000');
INSERT INTO `goStores_Vista_settings` (`fieldname`, `value`) VALUES ('store_access_key', 'df3dsfs3535dsfs345vds');
INSERT INTO `goStores_Vista_advertisements` (`adfile`, `template_id`, `position`, `status`) VALUES ('AD1566907235.png', 6, 3, 1); 
INSERT INTO `goStores_Vista_advertisements` (`adfile`, `template_id`, `position`, `status`) VALUES ('AD1566907257.png', 6, 4, 1);
INSERT INTO `goStores_Vista_advertisements` (`adfile`, `template_id`, `position`, `status`) VALUES ('AD1566907214.png', 6, 1, 1);
INSERT INTO `goStores_Vista_advertisements` (`adfile`, `template_id`, `position`, `status`) VALUES ('AD1566907225.png', 6, 2, 1);
INSERT INTO `goStores_Vista_banners` (`bannerfile`, `status`, `template_id`, `displayorder`, `bannertitle`, `bannerdata`) VALUES ('BAN1566912618.png', 1, 6, 3, 'This Week Offer', '10% Offer'); INSERT INTO `vista_banners` (`bannerfile`, `status`, `template_id`, `displayorder`, `bannertitle`, `bannerdata`) VALUES ('BAN1566912594.png', 1, 6, 2, 'Summer Offer', '15% Offer'); INSERT INTO `vista_banners` (`bannerfile`, `status`, `template_id`, `displayorder`, `bannertitle`, `bannerdata`) VALUES ('BAN1566909335.png', 1, 6, 1, 'Big Offer', '50% Offer');
